# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm7325-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter redwood vili,$(TARGET_DEVICE)),)

endif
